pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/pasinduweerarathne/jenkins-course.git', branch: 'jenkins-basics'
                sh "ls -ltr"
            }
        }

        stage('Setup') {
            steps {
                sh "pip install -r requirements.txt"
            }
        }

        stage('Test') {
            steps {
                sh "pytest"
            }
        }
    }
}


// pipeline {
//     agent any

//     stages {


//         stage('Setup') {
//             steps {
//                 withCredentials([usernamePassword(credentialsId: 'server-creds', usernameVariable: "myuser", passwordVariable: "mypassword")]) {

//                     sh '''
//                     echo ${myuser}
//                     echo ${mypassword}
//                     '''
//                 }

//                 sh "pip install -r requirements.txt"
            
//             }
//         }
//         stage('Test') {
//             steps {
//                 sh "pytest"
                
//             }
//         }    
//         stage('Deployment') {
//             input {
//                 message "Do you want to proceed further?"
//                 ok "Yes"
//             }
//             steps {
//                 echo "Running Deployment"
                
//             }
//         } 
        
            
//     }
// }