// ______________________________NESTED AND PARALLEL STAGES______________________________
pipeline {
    agent any

    stages {
        stage('link and format') {
            stages {
                stage('linting') {
                    steps {
                        echo 'linting code in nested stage'
                    }
                }

                stage('formatting') {
                    steps {
                        echo 'formatting code in nested stage'
                    }
                }
            }
        }

        stage('Setup') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'server-creds', usernameVariable: 'myUser', passwordVariable: 'myPass')]) {
                    bat '''
                    echo %myUser%
                    echo %myPass%
                    '''
                }
                
                bat "pip install -r 01-jenkins-basics\\requirements.txt"
            }
        }

        stage('Test') {
            steps {
                bat "pytest 01-jenkins-basics\\test_app.py"
            }
        }
    }
}



// ______________________________CREDENTIALS______________________________
// pipeline {
//     agent any

//     stages {
//         stage('Setup') {
//             steps {
//                 withCredentials([usernamePassword(credentialsId: 'server-creds', usernameVariable: 'myUser', passwordVariable: 'myPass')]) {
//                     bat '''
//                     echo %myUser%
//                     echo %myPass%
//                     '''
//                 }
                
//                 bat "pip install -r 01-jenkins-basics\\requirements.txt"
//             }
//         }

//         stage('Test') {
//             steps {
//                 bat "pytest 01-jenkins-basics\\test_app.py"
//             }
//         }
//     }
// }
// pipeline {
//     agent any

//     environment {
//        SERVER_CREDS = credentials("server-creds")
//     }

//     stages {
//         stage('Setup') {
//             steps {
//                 echo "My creds ${SERVER_CREDS}"
//                 echo "Username ${SERVER_CREDS_USR}"
//                 echo "Password ${SERVER_CREDS_PSW}"
//                 bat "pip install -r 01-jenkins-basics\\requirements.txt"
//             }
//         }

//         stage('Test') {
//             steps {
//                 bat "pytest 01-jenkins-basics\\test_app.py"
//             }
//         }
//     }
// }


// ______________________________ENVIRONMENT VARAIBLE______________________________
// pipeline {
//     agent any

//     stages {
//         // stage('Checkout') {
//         //     steps {
//         //         git url: 'https://github.com/pasinduweerarathne/jenkins-course.git', branch: 'jenkins-basics'
//         //         bat "dir"
//         //     }
//         // }

//         stage('Setup') {

//              environment {
//                 DB_HOST = '192.168.12.2'
//                 USERNAME = 'user1'
//                 PASSWROD = 'password'
//             }

//             steps {
//                 bat "pip install -r 01-jenkins-basics\\requirements.txt"
//                 echo "Database IP is: ${DB_HOST}"
//             }
//         }

//         stage('Test') {
//             steps {
//                 bat "pytest 01-jenkins-basics\\test_app.py"
//                 echo "Username is: ${USERNAME} and the password is: ${PASSWROD}"
//             }
//         }
//     }
// }




// pipeline {
//     agent any

//     stages {


//         stage('Setup') {
//             steps {
//                 withCredentials([usernamePassword(credentialsId: 'server-creds', usernameVariable: "myuser", passwordVariable: "mypassword")]) {

//                     sh '''
//                     echo ${myuser}
//                     echo ${mypassword}
//                     '''
//                 }

//                 sh "pip install -r requirements.txt"
            
//             }
//         }
//         stage('Test') {
//             steps {
//                 sh "pytest"
                
//             }
//         }    
//         stage('Deployment') {
//             input {
//                 message "Do you want to proceed further?"
//                 ok "Yes"
//             }
//             steps {
//                 echo "Running Deployment"
                
//             }
//         } 
        
            
//     }
// }